# Generated by Django 5.0.6 on 2024-07-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_image_blog_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='images',
            new_name='image',
        ),
    ]
